start=input(("Enter your name:"))
print(start)
print(type(start))
begin=input(("Enter your class:"))
print(begin)
print(type(begin))
first=input(("Enter your school name:"))
print(first)
print(type(first))
k=input(("Enter your hobby:"))
print(k)
print(type(k))
a=int(input("Enter your age:"))
print(a)
print(type(a))
