name = input("name:  ")
age = int(input("your age:  "))
hobby = input("hobby:  ")
classe = input("class")  # e added to class to not confuse with the class function
school = input("school")
print(f"my name is {name}, i am  {age} years old, my hobby is {hobby},my school is {school} my class is {classe}")
print(type(name))
print(type(age))
print(type(hobby))
print(type(classe))
print(type(school))
